// The submission store, with most of the attention on rejection: submissions
// are generated by agents, and this is the gate every one of them passes.
//
// What the gate does and does not promise is worth keeping straight in these
// tests. It bounds size, bounds hunks, and holds touched paths to the
// problem's policy. It does not make a patch safe to *build* -- only the
// sandbox does that.

#include "game_mcts/tournament_server/server/candidate_store.h"

#include <unistd.h>

#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <string>

#include "gtest/gtest.h"

namespace tournament_arena {
namespace {

auto MakeRequest(const std::string &name = "My Bot") -> proto::SubmitRequest {
  proto::SubmitRequest request;
  request.set_display_name(name);
  request.set_author("agent-1");
  request.set_game("risk2");
  request.set_entry_header("strategy.h");
  auto *file = request.add_files();
  file->set_path("strategy.h");
  file->set_content("#pragma once\n// strategy\n");
  return request;
}

// The rules a structured submission needs: where its files land, and a policy
// that admits that directory.
auto MakeRules() -> SubmissionRules {
  SubmissionRules rules;
  rules.files_submit_dir = "game_mcts/tournament_server/candidates";
  rules.game = "risk2";
  rules.policy.add_allow_paths("game_mcts/tournament_server/candidates/**");
  return rules;
}

class CandidateStoreTest : public ::testing::Test {
 protected:
  void SetUp() override {
    dir_ = std::filesystem::temp_directory_path() /
           ("candidate_store_" + std::to_string(::getpid()) + "_" +
            std::to_string(::testing::UnitTest::GetInstance()->random_seed()));
    std::filesystem::remove_all(dir_);
    store_ =
        std::make_unique<CandidateStore>(dir_, CandidateLimits{}, MakeRules());
  }

  void TearDown() override { std::filesystem::remove_all(dir_); }

  std::filesystem::path dir_;
  std::unique_ptr<CandidateStore> store_;
};

TEST_F(CandidateStoreTest, StoresSourcesAsReadableFiles) {
  std::string error;
  const auto candidate = store_->Create(MakeRequest(), "abc123", &error);
  ASSERT_TRUE(candidate.has_value()) << error;

  EXPECT_EQ(candidate->display_name(), "My Bot");
  EXPECT_EQ(candidate->base_commit(), "abc123");
  EXPECT_EQ(candidate->status(), proto::Candidate::PENDING);
  EXPECT_EQ(candidate->candidate_id().rfind("my-bot-", 0), 0u)
      << candidate->candidate_id();

  // Added files land on disk as real files, so a rival's source can be read and
  // grepped without a checkout. They are keyed by their repo path, because that
  // is what the patch actually touches.
  ASSERT_EQ(candidate->file_paths_size(), 2)
      << "the submitted header and its generated BUILD";
  const std::filesystem::path source =
      dir_ / candidate->candidate_id() / "src" /
      ("game_mcts/tournament_server/candidates/" + candidate->candidate_id() +
       "/strategy.h");
  ASSERT_TRUE(std::filesystem::exists(source));
  std::ifstream in(source);
  const std::string content((std::istreambuf_iterator<char>(in)),
                            std::istreambuf_iterator<char>());
  EXPECT_EQ(content, "#pragma once\n// strategy\n");

  const auto read_back =
      store_->ReadSource(candidate->candidate_id(),
                         "game_mcts/tournament_server/candidates/" +
                             candidate->candidate_id() + "/strategy.h",
                         &error);
  ASSERT_TRUE(read_back.has_value()) << error;
  EXPECT_EQ(*read_back, content);

  // The patch is the canonical stored form; the extracted files are a
  // convenience derived from it.
  const auto patch = store_->ReadPatch(candidate->candidate_id(), &error);
  ASSERT_TRUE(patch.has_value()) << error;
  EXPECT_NE(patch->find("+#pragma once"), std::string::npos) << *patch;
  EXPECT_NE(patch->find("new file mode"), std::string::npos) << *patch;
  // The BUILD is generated, never submitted: a submitter who could write their
  // own could write a genrule, and a genrule runs code at build time.
  EXPECT_NE(patch->find("/BUILD"), std::string::npos) << *patch;
  EXPECT_TRUE(
      std::filesystem::exists(dir_ / candidate->candidate_id() / "patch.diff"));
}

// A patch is the general form; the structured submission above is a
// convenience that becomes one.
TEST_F(CandidateStoreTest, AcceptsAPatchDirectly) {
  SubmissionRules rules;
  rules.policy.add_allow_paths("game_mcts/core/**");
  CandidateStore store(dir_, CandidateLimits{}, rules);

  proto::SubmitRequest request;
  request.set_display_name("Faster MCTS");
  request.set_patch(
      "diff --git a/game_mcts/core/mcts/mcts.h b/game_mcts/core/mcts/mcts.h\n"
      "--- a/game_mcts/core/mcts/mcts.h\n"
      "+++ b/game_mcts/core/mcts/mcts.h\n"
      "@@ -1,2 +1,2 @@\n"
      "-slow\n"
      "+fast\n");
  std::string error;
  const auto candidate = store.Create(request, "commit0", &error);
  ASSERT_TRUE(candidate.has_value()) << error;
  ASSERT_EQ(candidate->touched_paths_size(), 1);
  EXPECT_EQ(candidate->touched_paths(0), "game_mcts/core/mcts/mcts.h");
  // A modification adds no file, so there is nothing to extract. That is
  // honest: those lines live in the repo, not in the submission.
  EXPECT_EQ(candidate->file_paths_size(), 0);
}

TEST_F(CandidateStoreTest, HoldsPatchesToTheProblemsPathPolicy) {
  SubmissionRules rules;
  rules.policy.add_allow_paths("game_mcts/core/**");
  rules.policy.add_deny_paths("**/BUILD");
  CandidateStore store(dir_, CandidateLimits{}, rules);
  std::string error;

  const auto patch_touching = [](const std::string &path) {
    proto::SubmitRequest request;
    request.set_display_name("Probe");
    request.set_patch("diff --git a/" + path + " b/" + path + "\n--- a/" +
                      path + "\n+++ b/" + path + "\n@@ -1 +1 @@\n-a\n+b\n");
    return request;
  };

  EXPECT_TRUE(
      store.Validate(patch_touching("game_mcts/core/mcts/mcts.h"), &error))
      << error;

  // Outside allow_paths.
  EXPECT_FALSE(
      store.Validate(patch_touching("game_mcts/tools/bench.cc"), &error));
  EXPECT_NE(error.find("outside what this problem accepts"), std::string::npos)
      << error;

  // Denied even though it is inside allow_paths: deny wins, so a broad allow
  // can be narrowed without rewriting it. Being able to edit a BUILD file is
  // being able to run arbitrary code at build time.
  EXPECT_FALSE(store.Validate(patch_touching("game_mcts/core/BUILD"), &error));
  EXPECT_NE(error.find("excluded by this problem"), std::string::npos) << error;
}

TEST_F(CandidateStoreTest, RejectsAPatchThatEscapesTheRepo) {
  SubmissionRules rules;
  CandidateStore store(dir_, CandidateLimits{}, rules);
  proto::SubmitRequest request;
  request.set_display_name("Escape");
  request.set_patch(
      "diff --git a/../../etc/passwd b/../../etc/passwd\n"
      "new file mode 100644\n"
      "--- /dev/null\n"
      "+++ b/../../etc/passwd\n"
      "@@ -0,0 +1 @@\n"
      "+pwned\n");
  std::string error;
  EXPECT_FALSE(store.Validate(request, &error));
  EXPECT_NE(error.find(".."), std::string::npos) << error;
}

TEST_F(CandidateStoreTest, BoundsHunkCount) {
  SubmissionRules rules;
  rules.policy.set_max_hunks(1);
  CandidateStore store(dir_, CandidateLimits{}, rules);
  proto::SubmitRequest request;
  request.set_display_name("Sprawling");
  request.set_patch(
      "diff --git a/a.h b/a.h\n--- a/a.h\n+++ b/a.h\n"
      "@@ -1 +1 @@\n-a\n+b\n"
      "@@ -9 +9 @@\n-c\n+d\n");
  std::string error;
  EXPECT_FALSE(store.Validate(request, &error));
  EXPECT_NE(error.find("too many hunks"), std::string::npos) << error;
}

// The whole structured-submit path exists to produce a patch a worker can
// apply. Asserting on the patch text would only prove this file agrees with
// itself; the contract is git's.
TEST_F(CandidateStoreTest, SynthesizedPatchAppliesWithGit) {
  if (std::system("git --version > /dev/null 2>&1") != 0) {
    GTEST_SKIP() << "git is not available";
  }
  proto::SubmitRequest request = MakeRequest("Applies Cleanly");
  auto *helper = request.add_files();
  helper->set_path("nested/helper.h");
  helper->set_content("#pragma once\nint helper();\n");

  std::string error;
  const auto candidate = store_->Create(request, "commit0", &error);
  ASSERT_TRUE(candidate.has_value()) << error;
  const auto patch = store_->ReadPatch(candidate->candidate_id(), &error);
  ASSERT_TRUE(patch.has_value()) << error;

  const std::filesystem::path repo = dir_ / "fake_repo";
  std::filesystem::create_directories(repo);
  ASSERT_EQ(
      std::system(
          ("git -C " + repo.string() + " init -q > /dev/null 2>&1").c_str()),
      0);
  const std::filesystem::path patch_path = dir_ / "candidate.diff";
  {
    std::ofstream out(patch_path, std::ios::binary);
    out << *patch;
  }
  ASSERT_EQ(
      std::system(("git -C " + repo.string() + " apply " + patch_path.string())
                      .c_str()),
      0)
      << "git rejected the synthesized patch:\n"
      << *patch;

  // Everything lands where the generated build targets say it will.
  const std::filesystem::path root = repo /
                                     "game_mcts/tournament_server/candidates" /
                                     candidate->candidate_id();
  EXPECT_TRUE(std::filesystem::is_regular_file(root / "strategy.h"));
  EXPECT_TRUE(std::filesystem::is_regular_file(root / "nested/helper.h"));
  EXPECT_TRUE(std::filesystem::is_regular_file(root / "BUILD"));
}

TEST_F(CandidateStoreTest, IdsAreUniqueAcrossIdenticalNames) {
  std::string error;
  const auto first = store_->Create(MakeRequest(), "c", &error);
  const auto second = store_->Create(MakeRequest(), "c", &error);
  ASSERT_TRUE(first.has_value());
  ASSERT_TRUE(second.has_value());
  EXPECT_NE(first->candidate_id(), second->candidate_id());
  EXPECT_EQ(store_->size(), 2u);
}

TEST_F(CandidateStoreTest, SurvivesRestart) {
  std::string error;
  const auto candidate = store_->Create(MakeRequest(), "abc123", &error);
  ASSERT_TRUE(candidate.has_value()) << error;
  ASSERT_TRUE(store_->SetStatus(candidate->candidate_id(),
                                proto::Candidate::READY, ""));

  CandidateStore reopened(dir_);
  reopened.Load();
  EXPECT_EQ(reopened.size(), 1u);
  const auto loaded = reopened.Get(candidate->candidate_id());
  ASSERT_TRUE(loaded.has_value());
  EXPECT_EQ(loaded->display_name(), "My Bot");
  EXPECT_EQ(loaded->status(), proto::Candidate::READY);
  EXPECT_EQ(loaded->entry_header(), "strategy.h");

  const auto source =
      reopened.ReadSource(candidate->candidate_id(),
                          "game_mcts/tournament_server/candidates/" +
                              candidate->candidate_id() + "/strategy.h",
                          &error);
  ASSERT_TRUE(source.has_value()) << error;
}

TEST_F(CandidateStoreTest, BuildErrorIsTrimmedToTheCap) {
  CandidateLimits limits;
  limits.max_build_error_bytes = 64;
  CandidateStore store(dir_, limits, MakeRules());
  std::string error;
  const auto candidate = store.Create(MakeRequest(), "c", &error);
  ASSERT_TRUE(candidate.has_value()) << error;

  const std::string huge(10000, 'x');
  ASSERT_TRUE(store.SetStatus(candidate->candidate_id(),
                              proto::Candidate::BUILD_FAILED, huge));
  const auto loaded = store.Get(candidate->candidate_id());
  ASSERT_TRUE(loaded.has_value());
  EXPECT_EQ(loaded->build_error().size(), 64u);
  EXPECT_EQ(loaded->status(), proto::Candidate::BUILD_FAILED);
}

TEST_F(CandidateStoreTest, LineageMustReferToAKnownCandidate) {
  std::string error;
  const auto parent = store_->Create(MakeRequest("Parent"), "c", &error);
  ASSERT_TRUE(parent.has_value()) << error;

  proto::SubmitRequest child = MakeRequest("Child");
  child.set_parent_id(parent->candidate_id());
  EXPECT_TRUE(store_->Create(child, "c", &error).has_value()) << error;

  child.set_parent_id("does-not-exist");
  EXPECT_FALSE(store_->Create(child, "c", &error).has_value());
  EXPECT_NE(error.find("parent_id"), std::string::npos);
}

TEST_F(CandidateStoreTest, UnknownCandidateAndFileAreRejected) {
  std::string error;
  EXPECT_FALSE(store_->Get("nope").has_value());
  EXPECT_FALSE(store_->ReadSource("nope", "strategy.h", &error).has_value());

  const auto candidate = store_->Create(MakeRequest(), "c", &error);
  ASSERT_TRUE(candidate.has_value());
  // Reads are checked against the manifest, so a path that was never
  // submitted cannot be used to walk out of the candidate's directory.
  EXPECT_FALSE(store_
                   ->ReadSource(candidate->candidate_id(),
                                "../../../../etc/passwd", &error)
                   .has_value());
  EXPECT_NE(error.find("no file"), std::string::npos);
}

// --- path validation -------------------------------------------------------

TEST(ValidateSourcePathTest, AcceptsOrdinaryRelativeSources) {
  std::string error;
  for (const char *path : {"strategy.h", "sub/dir/helper.cc", "a_b-c.hpp",
                           "deep/nested/path/x.inl"}) {
    EXPECT_TRUE(ValidateSourcePath(path, &error)) << path << ": " << error;
  }
}

TEST(ValidateSourcePathTest, RejectsEscapesAndUnsupportedFiles) {
  const std::pair<const char *, const char *> cases[] = {
      {"", "empty"},
      {"/etc/passwd", "absolute"},
      {"../secrets.h", "parent traversal"},
      {"a/../../b.h", "parent traversal mid-path"},
      {"a//b.h", "double separator"},
      {"dir/", "trailing separator"},
      {"strategy.sh", "unsupported extension"},
      {"BUILD", "no extension"},
      {"strategy", "no extension"},
      {"win\\path.h", "backslash separator"},
      {"weird$name.h", "shell metacharacter"},
      {"space name.h", "whitespace"},
      {"semi;rm -rf.h", "command separator"},
  };
  for (const auto &[path, why] : cases) {
    std::string error;
    EXPECT_FALSE(ValidateSourcePath(path, &error)) << "accepted " << why;
    EXPECT_FALSE(error.empty()) << why;
  }
}

TEST(ValidateSourcePathTest, RejectsControlCharacters) {
  std::string error;
  std::string embedded_nul("nul.h");
  embedded_nul[3] = '\0';
  EXPECT_FALSE(ValidateSourcePath(embedded_nul, &error));
  EXPECT_FALSE(ValidateSourcePath("new\nline.h", &error));
}

TEST(ValidateSourcePathTest, RejectsOverlongPaths) {
  std::string error;
  EXPECT_FALSE(ValidateSourcePath(std::string(300, 'a') + ".h", &error));
}

// --- submission validation -------------------------------------------------

TEST_F(CandidateStoreTest, RejectsIncompleteSubmissions) {
  std::string error;

  proto::SubmitRequest no_name = MakeRequest();
  no_name.clear_display_name();
  EXPECT_FALSE(store_->Validate(no_name, &error));

  // The game is no longer the submitter's to state: one server runs one
  // problem, and the problem's config says which game that is.
  proto::SubmitRequest no_game = MakeRequest();
  no_game.clear_game();
  EXPECT_TRUE(store_->Validate(no_game, &error)) << error;

  // Neither form of submission present.
  proto::SubmitRequest nothing = MakeRequest();
  nothing.clear_files();
  EXPECT_FALSE(store_->Validate(nothing, &error));
  EXPECT_NE(error.find("patch or at least one source file"), std::string::npos)
      << error;

  // The entry header has to be something that was actually submitted,
  // otherwise the generated BUILD names a file that does not exist and the
  // agent gets an inscrutable compile error instead of a clear rejection.
  proto::SubmitRequest bad_entry = MakeRequest();
  bad_entry.set_entry_header("elsewhere.h");
  EXPECT_FALSE(store_->Validate(bad_entry, &error));
  EXPECT_NE(error.find("entry_header"), std::string::npos);

  proto::SubmitRequest duplicate = MakeRequest();
  *duplicate.add_files() = duplicate.files(0);
  EXPECT_FALSE(store_->Validate(duplicate, &error));
  EXPECT_NE(error.find("duplicate"), std::string::npos);
}

TEST_F(CandidateStoreTest, EnforcesSizeAndCountLimits) {
  CandidateLimits limits;
  limits.max_files = 2;
  limits.max_file_bytes = 100;
  limits.max_total_bytes = 150;
  CandidateStore store(dir_, limits, MakeRules());
  std::string error;

  proto::SubmitRequest too_many = MakeRequest();
  too_many.add_files()->set_path("b.h");
  too_many.add_files()->set_path("c.h");
  EXPECT_FALSE(store.Validate(too_many, &error));
  EXPECT_NE(error.find("too many files"), std::string::npos);

  proto::SubmitRequest too_big = MakeRequest();
  too_big.mutable_files(0)->set_content(std::string(200, 'x'));
  EXPECT_FALSE(store.Validate(too_big, &error));
  EXPECT_NE(error.find("too large"), std::string::npos);

  // The overall cap is on the synthesized patch, which is what actually gets
  // stored and dispatched -- not on the sum of the file contents.
  SubmissionRules tight = MakeRules();
  tight.policy.set_max_patch_bytes(120);
  CandidateStore small(dir_, CandidateLimits{}, tight);
  proto::SubmitRequest too_big_total = MakeRequest();
  too_big_total.mutable_files(0)->set_content(std::string(90, 'x') + "\n");
  EXPECT_FALSE(small.Validate(too_big_total, &error));
  EXPECT_NE(error.find("patch is too large"), std::string::npos) << error;
}

// A candidate that could name any bazel label could pull in a target with a
// genrule, and run arbitrary code as the sandbox user at build time.
TEST_F(CandidateStoreTest, RejectsDependenciesOutsideTheAllowlist) {
  std::string error;
  proto::SubmitRequest request = MakeRequest();
  request.add_extra_deps("//game_mcts/games/risk/strategies:risk_proposer");
  request.add_extra_deps("//game_mcts/core/mcts:mcts");
  EXPECT_TRUE(store_->Validate(request, &error)) << error;

  for (const char *dep :
       {"//game_mcts/tournament_server/server:matchmaker",
        "@some_external//:tool", "//:everything", "//scripts:fix_guards"}) {
    proto::SubmitRequest bad = MakeRequest();
    bad.add_extra_deps(dep);
    EXPECT_FALSE(store_->Validate(bad, &error)) << "accepted " << dep;
    EXPECT_NE(error.find("not allowed"), std::string::npos);
  }
}

TEST(SlugifyTest, ProducesReadableStableIds) {
  EXPECT_EQ(Slugify("My Bot"), "my-bot");
  EXPECT_EQ(Slugify("Deep  MCTS v2!"), "deep-mcts-v2");
  EXPECT_EQ(Slugify("  leading and trailing  "), "leading-and-trailing");
  EXPECT_EQ(Slugify("!!!"), "candidate");
  EXPECT_EQ(Slugify(""), "candidate");
  EXPECT_LE(Slugify(std::string(100, 'a')).size(), 40u);
}

}  // namespace
}  // namespace tournament_arena
