#include "game_mcts/tournament_server/server/generated_build.h"

#include <algorithm>
#include <sstream>

namespace tournament_arena {

namespace {

// Sources bazel compiles versus headers it only exposes. Anything else was
// already rejected by the store's extension allowlist.
auto IsCompiledSource(const std::string &path) -> bool {
  const auto dot = path.rfind('.');
  if (dot == std::string::npos) {
    return false;
  }
  const std::string ext = path.substr(dot);
  return ext == ".cc" || ext == ".cpp";
}

// Sorts and de-duplicates everything after the first entry, which is the
// harness dep and stays pinned at the top where a reader expects it.
void NormalizeDeps(std::vector<std::string> *deps) {
  if (deps->size() < 2) {
    return;
  }
  std::sort(deps->begin() + 1, deps->end());
  deps->erase(std::unique(deps->begin(), deps->end()), deps->end());
}

}  // namespace

auto CandidateTarget(const std::string &dir,
                     const std::string &candidate_id) -> std::string {
  return "//" + dir + "/" + candidate_id + ":bot";
}

auto GenerateCandidateBuild(
    const std::string &dir, const std::string &candidate_id,
    const proto::CandidateHarness &harness,
    const std::vector<std::string> &file_paths, const std::string &entry_header,
    const std::vector<std::string> &extra_deps) -> std::string {
  if (file_paths.empty() || entry_header.empty()) {
    return {};
  }
  if (std::find(file_paths.begin(), file_paths.end(), entry_header) ==
      file_paths.end()) {
    return {};
  }
  // Without these there is nothing to compile a submission against. That is a
  // misconfigured problem rather than a bad submission, but the answer is the
  // same: do not emit a BUILD that cannot work.
  if (harness.api_dep().empty() || harness.main_src().empty()) {
    return {};
  }
  const std::string &game_define = harness.game_define();

  std::vector<std::string> headers;
  std::vector<std::string> sources;
  for (const std::string &path : file_paths) {
    (IsCompiledSource(path) ? sources : headers).push_back(path);
  }
  std::sort(headers.begin(), headers.end());
  std::sort(sources.begin(), sources.end());

  std::vector<std::string> strategy_deps = {harness.api_dep()};
  for (const std::string &dep : extra_deps) {
    strategy_deps.push_back(dep);
  }
  NormalizeDeps(&strategy_deps);

  std::vector<std::string> bot_deps = {":strategy", harness.api_dep()};
  for (const std::string &dep : harness.bot_deps()) {
    bot_deps.push_back(dep);
  }
  NormalizeDeps(&bot_deps);

  const std::string entry_path = dir + "/" + candidate_id + "/" + entry_header;

  std::ostringstream build;
  build << "# Generated by the arena at submit time for candidate "
        << candidate_id << ".\n"
        << "# Do not edit: it is part of the submission's patch.\n\n"
           "load(\"@rules_cc//cc:cc_binary.bzl\", \"cc_binary\")\n"
           "load(\"@rules_cc//cc:cc_library.bzl\", \"cc_library\")\n\n"
           "package(default_visibility = [\"//visibility:private\"])\n\n"
           "cc_library(\n"
           "    name = \"strategy\",\n";

  build << "    hdrs = [\n";
  for (const std::string &path : headers) {
    build << "        \"" << path << "\",\n";
  }
  build << "    ],\n";
  if (!sources.empty()) {
    build << "    srcs = [\n";
    for (const std::string &path : sources) {
      build << "        \"" << path << "\",\n";
    }
    build << "    ],\n";
  }
  build << "    deps = [\n";
  for (const std::string &dep : strategy_deps) {
    build << "        \"" << dep << "\",\n";
  }
  build << "    ],\n";
  if (!game_define.empty()) {
    build << "    local_defines = [\"" << game_define << "\"],\n";
  }
  build << ")\n\n";

  // The harness main is compiled here rather than depended on: the game and
  // the entry header are local_defines, and those do not reach a prebuilt
  // library.
  build << "cc_binary(\n"
           "    name = \"bot\",\n"
        << "    srcs = [\"" << harness.main_src() << "\"],\n"
        << "    local_defines = [\n"
        << "        r'CANDIDATE_ENTRY_HEADER=\\\"" << entry_path << "\\\"',\n";
  if (!game_define.empty()) {
    build << "        \"" << game_define << "\",\n";
  }
  build << "    ],\n"
           "    deps = [\n";
  for (const std::string &dep : bot_deps) {
    build << "        \"" << dep << "\",\n";
  }
  build << "    ],\n"
           ")\n";
  return build.str();
}

}  // namespace tournament_arena
