#include "game_mcts/tournament_server/server/generated_build.h"

#include <algorithm>
#include <map>
#include <sstream>

namespace tournament_arena {

namespace {

// Sources bazel compiles versus headers it only exposes. Anything else was
// already rejected by the store's extension allowlist.
auto IsCompiledSource(const std::string &path) -> bool {
  const auto dot = path.rfind('.');
  if (dot == std::string::npos) {
    return false;
  }
  const std::string ext = path.substr(dot);
  return ext == ".cc" || ext == ".cpp";
}

}  // namespace

auto CandidateTarget(const std::string &dir,
                     const std::string &candidate_id) -> std::string {
  return "//" + dir + "/" + candidate_id + ":bot";
}

auto CandidateGameDefine(const std::string &game) -> std::string {
  if (game == "risk2") {
    return "CANDIDATE_GAME_RISK2";
  }
  if (game == "tictactoe") {
    return "CANDIDATE_GAME_TICTACTOE";
  }
  return {};
}

auto GenerateCandidateBuild(
    const std::string &dir, const std::string &candidate_id,
    const std::string &game, const std::vector<std::string> &file_paths,
    const std::string &entry_header,
    const std::vector<std::string> &extra_deps) -> std::string {
  if (file_paths.empty() || entry_header.empty()) {
    return {};
  }
  if (std::find(file_paths.begin(), file_paths.end(), entry_header) ==
      file_paths.end()) {
    return {};
  }
  const std::string game_define = CandidateGameDefine(game);
  if (game_define.empty()) {
    return {};
  }

  std::vector<std::string> headers;
  std::vector<std::string> sources;
  for (const std::string &path : file_paths) {
    (IsCompiledSource(path) ? sources : headers).push_back(path);
  }
  std::sort(headers.begin(), headers.end());
  std::sort(sources.begin(), sources.end());

  std::vector<std::string> deps = {
      "//game_mcts/tournament_server/candidate_api:candidate_api"};
  for (const std::string &dep : extra_deps) {
    deps.push_back(dep);
  }
  std::sort(deps.begin() + 1, deps.end());
  deps.erase(std::unique(deps.begin(), deps.end()), deps.end());

  const std::string entry_path = dir + "/" + candidate_id + "/" + entry_header;

  std::ostringstream build;
  build << "# Generated by the arena at submit time for candidate "
        << candidate_id << ".\n"
        << "# Do not edit: it is part of the submission's patch.\n\n"
           "load(\"@rules_cc//cc:cc_binary.bzl\", \"cc_binary\")\n"
           "load(\"@rules_cc//cc:cc_library.bzl\", \"cc_library\")\n\n"
           "package(default_visibility = [\"//visibility:private\"])\n\n"
           "cc_library(\n"
           "    name = \"strategy\",\n";

  build << "    hdrs = [\n";
  for (const std::string &path : headers) {
    build << "        \"" << path << "\",\n";
  }
  build << "    ],\n";
  if (!sources.empty()) {
    build << "    srcs = [\n";
    for (const std::string &path : sources) {
      build << "        \"" << path << "\",\n";
    }
    build << "    ],\n";
  }
  build << "    deps = [\n";
  for (const std::string &dep : deps) {
    build << "        \"" << dep << "\",\n";
  }
  build << "    ],\n"
        << "    local_defines = [\"" << game_define << "\"],\n"
        << ")\n\n";

  // candidate_main.cc is compiled here rather than depended on: the game and
  // the entry header are local_defines, and those do not reach a prebuilt
  // library.
  build
      << "cc_binary(\n"
         "    name = \"bot\",\n"
         "    srcs = "
         "[\"//game_mcts/tournament_server/"
         "candidate_api:candidate_main.cc\"],\n"
      << "    local_defines = [\n"
      << "        r'CANDIDATE_ENTRY_HEADER=\\\"" << entry_path << "\\\"',\n"
      << "        \"" << game_define << "\",\n"
      << "    ],\n"
         "    deps = [\n"
         "        \":strategy\",\n"
         "        "
         "\"//game_mcts/tournament_server/candidate_api:candidate_api\",\n"
         "        \"//game_mcts/tournament_server/client:remote_client\",\n"
         "        "
         "\"//game_mcts/tournament_server/proto:tournament_broker_cc_grpc\",\n"
         "        \"@abseil-cpp//absl/flags:flag\",\n"
         "        \"@abseil-cpp//absl/flags:parse\",\n"
         "        \"@abseil-cpp//absl/log\",\n"
         "        \"@abseil-cpp//absl/log:initialize\",\n"
         "        \"@grpc//:grpc++\",\n"
         "    ],\n"
         ")\n";
  return build.str();
}

}  // namespace tournament_arena
