#!/usr/bin/env python3
"""Convert template string files to a C++ source with lookup functions.

Usage:
    python3 template_to_cpp.py -o templates.cpp tmpl_48_2.txt tmpl_48_3.txt ...

The text_width is parsed from each filename (tmpl_{width}_{text_width}.txt).
For each .txt file, the corresponding .npz.npy file is loaded to provide
a per-cell territory mapping.

The generated .cpp provides:

    std::span<const AsciiBoardSegmentT>
    GetAsciiBoardTemplate(int width, int text_width);

    TerritoryMap GetTerritoryMap(int width, int text_width);

    std::span<const BoardInfo> GetAvailableBoardTemplates();
"""

import argparse
import pathlib
import re
import struct
import sys

_SEGMENT_RE = re.compile(
    r'\x1b\[4\$\{COLOR_(\d+)\}m'
    r'|\$\{UNITS_(\d+)\}'
)

_FILENAME_RE = re.compile(r'tmpl_(\d+)_(\d+)')


def parse_template(template_str: str, text_width: int):
    segments = []
    pos = 0
    for m in _SEGMENT_RE.finditer(template_str):
        if m.start() > pos:
            segments.append(('string', template_str[pos:m.start()]))
        if m.group(1) is not None:
            segments.append(('color', int(m.group(1))))
        else:
            segments.append(('units', int(m.group(2)), text_width))
        pos = m.end()
    if pos < len(template_str):
        segments.append(('string', template_str[pos:]))
    return segments


def _escape_cpp(s: str) -> str:
    out = []
    for ch in s:
        if ch == '\\':
            out.append('\\\\')
        elif ch == '"':
            out.append('\\"')
        elif ch == '\n':
            out.append('\\n')
        elif ch == '\x1b':
            out.append('\\x1b')
        elif ch == '\t':
            out.append('\\t')
        elif ord(ch) < 0x20:
            out.append(f'\\x{ord(ch):02x}')
        else:
            out.append(ch)
    return ''.join(out)


def _parse_filename(path: str):
    m = _FILENAME_RE.search(pathlib.Path(path).stem)
    if not m:
        raise ValueError(f'Cannot parse width/text_width from filename: {path}')
    return int(m.group(1)), int(m.group(2))


def _read_npy_uint8(path: str):
    """Read a uint8 2D npy file without numpy."""
    with open(path, 'rb') as f:
        magic = f.read(6)
        assert magic == b'\x93NUMPY', f'Bad npy magic in {path}'
        major = struct.unpack('B', f.read(1))[0]
        f.read(1)  # minor
        if major == 1:
            header_len = struct.unpack('<H', f.read(2))[0]
        else:
            header_len = struct.unpack('<I', f.read(4))[0]
        header = f.read(header_len).decode('latin1').strip()
        shape_match = re.search(r"'shape':\s*\((\d+),\s*(\d+)\)", header)
        assert shape_match, f'Cannot parse shape from {path}: {header}'
        rows = int(shape_match.group(1))
        cols = int(shape_match.group(2))
        data = list(f.read(rows * cols))
        assert len(data) == rows * cols
    return rows, cols, data


def _emit_segment_array(segments, name: str) -> list[str]:
    lines = [f'static constexpr AsciiBoardSegmentT {name}[] = {{']
    for seg in segments:
        if seg[0] == 'string':
            lines.append(f'    StringEntry{{"{_escape_cpp(seg[1])}"}},')
        elif seg[0] == 'color':
            lines.append(f'    TerritoryColor{{{seg[1]}}},')
        elif seg[0] == 'units':
            lines.append(
                f'    TerritoryTroopCounter{{0, {seg[1]}, {seg[2]}}},')
    lines.append('};')
    return lines


def _emit_cells_array(rows, cols, data, name: str) -> list[str]:
    lines = [f'const uint8_t {name}[] = {{']
    for r in range(rows):
        row_data = data[r * cols:(r + 1) * cols]
        line = '    ' + ', '.join(str(v) for v in row_data) + ','
        lines.append(line)
    lines.append('};')
    return lines


def generate_multi_cpp(entries) -> str:
    """Generate a .cpp with all template arrays and lookup functions.

    entries: list of (width, text_width, seg_name, segments,
                      cell_name, rows, cols, cell_data)
    """
    lines = [
        '// Auto-generated by template_to_cpp.py — do not edit.',
        '#include "game_mcts/cpp/risk/ascii_board.h"',
        '',
        'namespace risk_game {',
        'namespace {',
        '',
    ]

    for e in entries:
        width, text_width, seg_name, segments, cell_name, rows, cols, data = e
        lines.extend(_emit_segment_array(segments, seg_name))
        lines.append('')
        lines.extend(_emit_cells_array(rows, cols, data, cell_name))
        lines.append('')

    # Lookup table.
    lines.append('struct Entry {')
    lines.append('  int width;')
    lines.append('  int text_width;')
    lines.append('  const AsciiBoardSegmentT* segments;')
    lines.append('  size_t num_segments;')
    lines.append('  const uint8_t* cells;')
    lines.append('  int rows;')
    lines.append('  int cols;')
    lines.append('};')
    lines.append('')
    lines.append('const Entry kEntries[] = {')
    for e in entries:
        width, text_width, seg_name, segments, cell_name, rows, cols, data = e
        lines.append(
            f'    {{{width}, {text_width}, {seg_name},'
            f' sizeof({seg_name}) / sizeof({seg_name}[0]),'
            f' {cell_name}, {rows}, {cols}}},')
    lines.append('};')
    lines.append('')

    # BoardInfo table.
    lines.append(f'const BoardInfo kBoardInfos[] = {{')
    for e in entries:
        width, text_width, _, _, _, rows, cols, _ = e
        lines.append(f'    {{{width}, {text_width}, {cols}, {rows}}},')
    lines.append('};')
    lines.append('')
    lines.append('}  // namespace')
    lines.append('')

    # GetAsciiBoardTemplate.
    lines.append(
        'std::span<const AsciiBoardSegmentT> GetAsciiBoardTemplate(')
    lines.append('    int width, int text_width) {')
    lines.append('  for (const auto& e : kEntries) {')
    lines.append(
        '    if (e.width == width && e.text_width == text_width) {')
    lines.append('      return {e.segments, e.num_segments};')
    lines.append('    }')
    lines.append('  }')
    lines.append('  return {};')
    lines.append('}')
    lines.append('')

    # GetTerritoryMap.
    lines.append('TerritoryMap GetTerritoryMap(int width, int text_width) {')
    lines.append('  for (const auto& e : kEntries) {')
    lines.append(
        '    if (e.width == width && e.text_width == text_width) {')
    lines.append('      return {e.cells, e.rows, e.cols};')
    lines.append('    }')
    lines.append('  }')
    lines.append('  return {nullptr, 0, 0};')
    lines.append('}')
    lines.append('')

    # GetAvailableBoardTemplates.
    lines.append(
        'std::span<const BoardInfo> GetAvailableBoardTemplates() {')
    lines.append('  return kBoardInfos;')
    lines.append('}')
    lines.append('')
    lines.append('}  // namespace risk_game')
    lines.append('')
    return '\n'.join(lines)


def main():
    parser = argparse.ArgumentParser(
        description='Convert template strings to C++ lookup source')
    parser.add_argument('inputs', nargs='+',
                        help='Input template string files (.txt)')
    parser.add_argument('-o', '--output', required=True,
                        help='Output .cpp file')
    args = parser.parse_args()

    # Filter to .txt files only (npy files may also appear in args).
    txt_files = [p for p in args.inputs if p.endswith('.txt')]

    entries = []
    for path in sorted(txt_files):
        width, text_width = _parse_filename(path)
        with open(path, 'r') as f:
            template_str = f.read()
        seg_name = f'kSegs_{width}_{text_width}'
        segments = parse_template(template_str, text_width)

        npy_path = path.replace('.txt', '.npz.npy')
        rows, cols, cell_data = _read_npy_uint8(npy_path)
        cell_name = f'kCells_{width}_{text_width}'

        entries.append((width, text_width, seg_name, segments,
                        cell_name, rows, cols, cell_data))

    entries.sort(key=lambda e: (e[0], e[1]))
    cpp_code = generate_multi_cpp(entries)
    with open(args.output, 'w') as f:
        f.write(cpp_code)

    print(f'Wrote {len(entries)} templates to {args.output}', file=sys.stderr)


if __name__ == '__main__':
    main()
