// The candidate store, with most of the attention on rejection: submissions
// are generated by agents, and the path allowlist is the only thing standing
// between a submission and the sandbox's filesystem.

#include "cpp/tournament_server/candidate_store.h"

#include <filesystem>
#include <fstream>
#include <string>

#include "gtest/gtest.h"

#include <unistd.h>

namespace tournament_arena {
namespace {

auto MakeRequest(const std::string &name = "My Bot")
    -> proto::SubmitRequest {
  proto::SubmitRequest request;
  request.set_display_name(name);
  request.set_author("agent-1");
  request.set_game("risk2");
  request.set_entry_header("strategy.h");
  auto *file = request.add_files();
  file->set_path("strategy.h");
  file->set_content("#pragma once\n// strategy\n");
  return request;
}

class CandidateStoreTest : public ::testing::Test {
 protected:
  void SetUp() override {
    dir_ = std::filesystem::temp_directory_path() /
           ("candidate_store_" + std::to_string(::getpid()) + "_" +
            std::to_string(
                ::testing::UnitTest::GetInstance()->random_seed()));
    std::filesystem::remove_all(dir_);
    store_ = std::make_unique<CandidateStore>(dir_);
  }

  void TearDown() override { std::filesystem::remove_all(dir_); }

  std::filesystem::path dir_;
  std::unique_ptr<CandidateStore> store_;
};

TEST_F(CandidateStoreTest, StoresSourcesAsReadableFiles) {
  std::string error;
  const auto candidate = store_->Create(MakeRequest(), "abc123", &error);
  ASSERT_TRUE(candidate.has_value()) << error;

  EXPECT_EQ(candidate->display_name(), "My Bot");
  EXPECT_EQ(candidate->base_commit(), "abc123");
  EXPECT_EQ(candidate->status(), proto::Candidate::PENDING);
  EXPECT_EQ(candidate->candidate_id().rfind("my-bot-", 0), 0u)
      << candidate->candidate_id();

  // Sources land on disk as real files, so they can be read without the store.
  const std::filesystem::path source =
      dir_ / candidate->candidate_id() / "src" / "strategy.h";
  ASSERT_TRUE(std::filesystem::exists(source));
  std::ifstream in(source);
  const std::string content((std::istreambuf_iterator<char>(in)),
                            std::istreambuf_iterator<char>());
  EXPECT_EQ(content, "#pragma once\n// strategy\n");

  const auto read_back =
      store_->ReadSource(candidate->candidate_id(), "strategy.h", &error);
  ASSERT_TRUE(read_back.has_value()) << error;
  EXPECT_EQ(*read_back, content);
}

TEST_F(CandidateStoreTest, IdsAreUniqueAcrossIdenticalNames) {
  std::string error;
  const auto first = store_->Create(MakeRequest(), "c", &error);
  const auto second = store_->Create(MakeRequest(), "c", &error);
  ASSERT_TRUE(first.has_value());
  ASSERT_TRUE(second.has_value());
  EXPECT_NE(first->candidate_id(), second->candidate_id());
  EXPECT_EQ(store_->size(), 2u);
}

TEST_F(CandidateStoreTest, SurvivesRestart) {
  std::string error;
  const auto candidate = store_->Create(MakeRequest(), "abc123", &error);
  ASSERT_TRUE(candidate.has_value()) << error;
  ASSERT_TRUE(store_->SetStatus(candidate->candidate_id(),
                                proto::Candidate::READY, ""));

  CandidateStore reopened(dir_);
  reopened.Load();
  EXPECT_EQ(reopened.size(), 1u);
  const auto loaded = reopened.Get(candidate->candidate_id());
  ASSERT_TRUE(loaded.has_value());
  EXPECT_EQ(loaded->display_name(), "My Bot");
  EXPECT_EQ(loaded->status(), proto::Candidate::READY);
  EXPECT_EQ(loaded->entry_header(), "strategy.h");

  const auto source =
      reopened.ReadSource(candidate->candidate_id(), "strategy.h", &error);
  ASSERT_TRUE(source.has_value()) << error;
}

TEST_F(CandidateStoreTest, BuildErrorIsTrimmedToTheCap) {
  CandidateLimits limits;
  limits.max_build_error_bytes = 64;
  CandidateStore store(dir_, limits);
  std::string error;
  const auto candidate = store.Create(MakeRequest(), "c", &error);
  ASSERT_TRUE(candidate.has_value()) << error;

  const std::string huge(10000, 'x');
  ASSERT_TRUE(store.SetStatus(candidate->candidate_id(),
                              proto::Candidate::BUILD_FAILED, huge));
  const auto loaded = store.Get(candidate->candidate_id());
  ASSERT_TRUE(loaded.has_value());
  EXPECT_EQ(loaded->build_error().size(), 64u);
  EXPECT_EQ(loaded->status(), proto::Candidate::BUILD_FAILED);
}

TEST_F(CandidateStoreTest, LineageMustReferToAKnownCandidate) {
  std::string error;
  const auto parent = store_->Create(MakeRequest("Parent"), "c", &error);
  ASSERT_TRUE(parent.has_value()) << error;

  proto::SubmitRequest child = MakeRequest("Child");
  child.set_parent_id(parent->candidate_id());
  EXPECT_TRUE(store_->Create(child, "c", &error).has_value()) << error;

  child.set_parent_id("does-not-exist");
  EXPECT_FALSE(store_->Create(child, "c", &error).has_value());
  EXPECT_NE(error.find("parent_id"), std::string::npos);
}

TEST_F(CandidateStoreTest, UnknownCandidateAndFileAreRejected) {
  std::string error;
  EXPECT_FALSE(store_->Get("nope").has_value());
  EXPECT_FALSE(store_->ReadSource("nope", "strategy.h", &error).has_value());

  const auto candidate = store_->Create(MakeRequest(), "c", &error);
  ASSERT_TRUE(candidate.has_value());
  // Reads are checked against the manifest, so a path that was never
  // submitted cannot be used to walk out of the candidate's directory.
  EXPECT_FALSE(
      store_->ReadSource(candidate->candidate_id(), "../../../../etc/passwd",
                         &error)
          .has_value());
  EXPECT_NE(error.find("no file"), std::string::npos);
}

// --- path validation -------------------------------------------------------

TEST(ValidateSourcePathTest, AcceptsOrdinaryRelativeSources) {
  std::string error;
  for (const char *path : {"strategy.h", "sub/dir/helper.cc", "a_b-c.hpp",
                           "deep/nested/path/x.inl"}) {
    EXPECT_TRUE(ValidateSourcePath(path, &error)) << path << ": " << error;
  }
}

TEST(ValidateSourcePathTest, RejectsEscapesAndUnsupportedFiles) {
  const std::pair<const char *, const char *> cases[] = {
      {"", "empty"},
      {"/etc/passwd", "absolute"},
      {"../secrets.h", "parent traversal"},
      {"a/../../b.h", "parent traversal mid-path"},
      {"a//b.h", "double separator"},
      {"dir/", "trailing separator"},
      {"strategy.sh", "unsupported extension"},
      {"BUILD", "no extension"},
      {"strategy", "no extension"},
      {"win\\path.h", "backslash separator"},
      {"weird$name.h", "shell metacharacter"},
      {"space name.h", "whitespace"},
      {"semi;rm -rf.h", "command separator"},
  };
  for (const auto &[path, why] : cases) {
    std::string error;
    EXPECT_FALSE(ValidateSourcePath(path, &error)) << "accepted " << why;
    EXPECT_FALSE(error.empty()) << why;
  }
}

TEST(ValidateSourcePathTest, RejectsControlCharacters) {
  std::string error;
  std::string embedded_nul("nul.h");
  embedded_nul[3] = '\0';
  EXPECT_FALSE(ValidateSourcePath(embedded_nul, &error));
  EXPECT_FALSE(ValidateSourcePath("new\nline.h", &error));
}

TEST(ValidateSourcePathTest, RejectsOverlongPaths) {
  std::string error;
  EXPECT_FALSE(ValidateSourcePath(std::string(300, 'a') + ".h", &error));
}

// --- submission validation -------------------------------------------------

TEST_F(CandidateStoreTest, RejectsIncompleteSubmissions) {
  std::string error;

  proto::SubmitRequest no_name = MakeRequest();
  no_name.clear_display_name();
  EXPECT_FALSE(store_->Validate(no_name, &error));

  proto::SubmitRequest no_game = MakeRequest();
  no_game.clear_game();
  EXPECT_FALSE(store_->Validate(no_game, &error));

  proto::SubmitRequest no_files = MakeRequest();
  no_files.clear_files();
  EXPECT_FALSE(store_->Validate(no_files, &error));

  // The entry header has to be something that was actually submitted,
  // otherwise the generated BUILD names a file that does not exist and the
  // agent gets an inscrutable compile error instead of a clear rejection.
  proto::SubmitRequest bad_entry = MakeRequest();
  bad_entry.set_entry_header("elsewhere.h");
  EXPECT_FALSE(store_->Validate(bad_entry, &error));
  EXPECT_NE(error.find("entry_header"), std::string::npos);

  proto::SubmitRequest duplicate = MakeRequest();
  *duplicate.add_files() = duplicate.files(0);
  EXPECT_FALSE(store_->Validate(duplicate, &error));
  EXPECT_NE(error.find("duplicate"), std::string::npos);
}

TEST_F(CandidateStoreTest, EnforcesSizeAndCountLimits) {
  CandidateLimits limits;
  limits.max_files = 2;
  limits.max_file_bytes = 100;
  limits.max_total_bytes = 150;
  CandidateStore store(dir_, limits);
  std::string error;

  proto::SubmitRequest too_many = MakeRequest();
  too_many.add_files()->set_path("b.h");
  too_many.add_files()->set_path("c.h");
  EXPECT_FALSE(store.Validate(too_many, &error));
  EXPECT_NE(error.find("too many files"), std::string::npos);

  proto::SubmitRequest too_big = MakeRequest();
  too_big.mutable_files(0)->set_content(std::string(200, 'x'));
  EXPECT_FALSE(store.Validate(too_big, &error));
  EXPECT_NE(error.find("too large"), std::string::npos);

  proto::SubmitRequest too_big_total = MakeRequest();
  too_big_total.mutable_files(0)->set_content(std::string(90, 'x'));
  auto *second = too_big_total.add_files();
  second->set_path("b.h");
  second->set_content(std::string(90, 'x'));
  EXPECT_FALSE(store.Validate(too_big_total, &error));
  EXPECT_NE(error.find("too large"), std::string::npos);
}

// A candidate that could name any bazel label could pull in a target with a
// genrule, and run arbitrary code as the sandbox user at build time.
TEST_F(CandidateStoreTest, RejectsDependenciesOutsideTheAllowlist) {
  std::string error;
  proto::SubmitRequest request = MakeRequest();
  request.add_extra_deps("//game_mcts/cpp/risk/strategies:risk_proposer");
  request.add_extra_deps("//game_mcts/cpp/mcts:mcts");
  EXPECT_TRUE(store_->Validate(request, &error)) << error;

  for (const char *dep : {"//game_mcts/tournament_server:matchmaker",
                          "@some_external//:tool", "//:everything",
                          "//scripts:fix_guards"}) {
    proto::SubmitRequest bad = MakeRequest();
    bad.add_extra_deps(dep);
    EXPECT_FALSE(store_->Validate(bad, &error)) << "accepted " << dep;
    EXPECT_NE(error.find("not allowed"), std::string::npos);
  }
}

TEST(SlugifyTest, ProducesReadableStableIds) {
  EXPECT_EQ(Slugify("My Bot"), "my-bot");
  EXPECT_EQ(Slugify("Deep  MCTS v2!"), "deep-mcts-v2");
  EXPECT_EQ(Slugify("  leading and trailing  "), "leading-and-trailing");
  EXPECT_EQ(Slugify("!!!"), "candidate");
  EXPECT_EQ(Slugify(""), "candidate");
  EXPECT_LE(Slugify(std::string(100, 'a')).size(), 40u);
}

}  // namespace
}  // namespace tournament_arena
