#!/usr/bin/env python3
"""Stages the candidates a play page can face, and what it knows of them.

  python3 web/stage.py ~/.arena/risk2-swiss-<time> [--only claude-v21,agy-v08]

Copies each version's files from a Swiss re-rank's data dir
(candidates/<id>/src/bots/<id>/) and bots/reference into web/bots/<id>/, and
writes web/bots/BUILD (one wasm_bot each, see web/wasm.bzl) and
web/bots/manifest.json: every entry with its participant, version, whether it
is the one on the board, and its Swiss rating from the run's swiss.tsv.
web/bots/ is generated: git ignores it.
"""

import argparse
import json
import pathlib
import re
import shutil

WEB = pathlib.Path(__file__).resolve().parent
BOTS = WEB / "bots"
REFERENCE = WEB.parent / "bots" / "reference"


def ratings(data_dir):
    """The last snapshot of swiss.tsv: {id: (mu, sigma)}."""
    last = {}
    tsv = data_dir / "swiss.tsv"
    if tsv.exists():
        for line in tsv.read_text().splitlines():
            f = line.split("\t")
            if f[0] == "S":
                last[f[2]] = (int(f[1]), float(f[3]), float(f[4]))
    newest = max((r for r, _, _ in last.values()), default=0)
    return {i: (mu, sd) for i, (r, mu, sd) in last.items() if r == newest}


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("data_dir", type=pathlib.Path)
    parser.add_argument("--only", default="", help="comma-separated ids")
    args = parser.parse_args()
    only = set(filter(None, args.only.split(",")))

    sources = {"reference": REFERENCE}
    for d in sorted((args.data_dir / "candidates").iterdir()):
        if d.is_dir() and not d.name.endswith(".staged"):
            sources[d.name] = d / "src" / "bots" / d.name
    if only:
        sources = {i: s for i, s in sources.items() if i in only}

    shutil.rmtree(BOTS, ignore_errors=True)
    BOTS.mkdir()
    rated = ratings(args.data_dir)
    versions = {}
    for i in sources:
        m = re.fullmatch(r"(.+)-v(\d+)", i)
        if m:
            versions.setdefault(m[1], []).append(int(m[2]))
    entries = []
    for i, src in sources.items():
        (BOTS / i).mkdir()
        for f in src.iterdir():
            if f.suffix in (".h", ".cc"):
                shutil.copy2(f, BOTS / i / f.name)
        m = re.fullmatch(r"(.+)-v(\d+)", i)
        participant, version = (m[1], int(m[2])) if m else (i, 0)
        mu, sigma = rated.get(i, (None, None))
        entries.append({
            "id": i,
            "participant": participant,
            "version": version,
            "live": bool(m) and version == max(versions[participant]),
            "mu": mu,
            "sigma": sigma,
        })
    entries.sort(key=lambda e: -(e["mu"] if e["mu"] is not None else -1e9))

    (BOTS / "BUILD").write_text(
        "# Generated by web/stage.py: do not edit.\n\n"
        'load("//web:wasm.bzl", "wasm_bot")\n\n'
        'package(default_visibility = ["//visibility:public"])\n\n' +
        "".join(f'wasm_bot(name = "{i}")\n' for i in sources) +
        '\nfilegroup(\n    name = "wasm",\n    srcs = [\n' +
        "".join(f'        ":{i}_wasm",\n' for i in sources) +
        '    ],\n    tags = ["manual"],\n)\n')
    (BOTS / "manifest.json").write_text(json.dumps(entries, indent=1) + "\n")
    print(f"staged {len(entries)} candidate(s) into {BOTS}")


if __name__ == "__main__":
    main()
